// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMCslNeSjiMzFFmjpfGJj7G8mPZTgEOL4',
    appId: '1:384359260662:web:3354b9da9c6d33a112a7d7',
    messagingSenderId: '384359260662',
    projectId: 'udemy-store-6bac1',
    authDomain: 'udemy-store-6bac1.firebaseapp.com',
    storageBucket: 'udemy-store-6bac1.appspot.com',
    measurementId: 'G-8CGVEZZY2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK-waMuPPs52MAs8OyG2IaI7_HL6p4ZOg',
    appId: '1:384359260662:android:4efd7e6c27895a7112a7d7',
    messagingSenderId: '384359260662',
    projectId: 'udemy-store-6bac1',
    storageBucket: 'udemy-store-6bac1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUPlWUfBESUh1nCTEGloHoBa41rczrmA',
    appId: '1:384359260662:ios:ca2f0143910e738712a7d7',
    messagingSenderId: '384359260662',
    projectId: 'udemy-store-6bac1',
    storageBucket: 'udemy-store-6bac1.appspot.com',
    iosClientId: '384359260662-it9r1c6a7gtl0ghpo2fc64b6l3aq1sdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhUPlWUfBESUh1nCTEGloHoBa41rczrmA',
    appId: '1:384359260662:ios:ca2f0143910e738712a7d7',
    messagingSenderId: '384359260662',
    projectId: 'udemy-store-6bac1',
    storageBucket: 'udemy-store-6bac1.appspot.com',
    iosClientId: '384359260662-it9r1c6a7gtl0ghpo2fc64b6l3aq1sdt.apps.googleusercontent.com',
    iosBundleId: 'com.example.multiStore',
  );
}
